### ISSUE TITLE
Feature Request: support for NUI (another user interface package)

### ISSUE THREAD

**Issue by rodolfoksveiga** [chrisgrieser/nvim-genghis#11]
### Feature Requested

First things first, thanks for developing this package, it's exactly the translation of `eunuch.vim` in Lua I was looking for.

I would like to know if the community has interest on having also support for `nui.nvim`, like `dressing.nvim`.

I use `nui.nvim` as my main UI in NeoVIM and I have already locally implemented the UI from  `nvim-genghis` with `nui.vim`. If the community wants this feature, I would be happy to share my solution or open a pull request.

Once more, thanks for the work you've done so far.

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/41191959/220146178-b9147031-3306-432c-8975-1cf356575605.png)

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
Thanks for the nice words!

sure, I don't use nui myself, but having support for it would indeed be useful for some users. So you are very welcome to add it via PR!

**Comment by rodolfoksveiga** [comment]
Still didn't have time to touch it, but as soon as I make it sure nothing is broken I open a PR.
