### ISSUE TITLE
[Bug]: Trash fails on sometimes

### ISSUE THREAD

**Issue by fritzblue** [chrisgrieser/nvim-genghis#12]
### Bug Description

Trying `:Trash` on linux I get:

`Could not delete file: <path>: No such file or directory`

At first I thought this was due to the underlying directory being behind a symlink, but it seems to happen regardless.

### neovim version

```Text
0.8.3
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
yeah, I also get that sometimes on macOS, but I could not determine the issue / reproduce it reliably to figure out what's wrong 😕
