### ISSUE TITLE
[Bug]: Unable to use directory auto completion, filename has mixed slashes on Windows

### ISSUE THREAD

**Issue by DeadlySquad13** [chrisgrieser/nvim-genghis#14]
### Bug Description

When I try to move file on Windows, it fills input with full filename that has mixed slashes ('/' and '\\') and autocomplete window doesn't show up neither automatically nor manually.

If I change all paths to '\\', it will start working (see 2nd screenshot).

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/46250621/224489212-766e26ce-cc5e-4758-a42b-ed2840fb8e86.png)
![image](https://user-images.githubusercontent.com/46250621/224489246-db757039-95b3-498c-a62f-4c6036a4baf0.png)

### To Reproduce

1. `:Move`
2. Try to autocomplete while on Windows.

### neovim version

```Text
0.9.0-dev-1051
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
Hmm, I haven't touched a windows device in more than a decade, so I am not really sure how Windows paths work. 

I suspect someone else will have to help out here >.<
