### ISSUE TITLE
Feature Request: Remove/Delete commands

### ISSUE THREAD

**Issue by JanValiska** [chrisgrieser/nvim-genghis#24]
### Feature Requested

I don't get it why so important commands as Remove or Delete are not part of this plugin. The Eunuch plugin have it.

![obrázok](https://github.com/chrisgrieser/nvim-genghis/assets/755186/9c0c6709-37b3-496d-bdbf-6aa1d29e80b4)

Or am I missing something?

Thank you.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
They are part of this plugin, it's just called `trashFile`, since this plugin sends stuff to the trash rather than irreversibly deleting them like eunuch 🙈

first bullet: https://github.com/chrisgrieser/nvim-genghis#file-utility-commands

**Comment by JanValiska** [comment]
Thank you for explanation. I totally missed/not realized that point. Thanks for nice plugin.
