### ISSUE TITLE
[Bug]: :New makes files relative to neovim's working directory, but tries to edit a new file relative to directory of currently-open file

### ISSUE THREAD

**Issue by BeauSLM** [chrisgrieser/nvim-genghis#29]
### Bug Description

I'll refer to the directory Neovim was opened in as `{working_dir}` i.e. `cd working_dir ; nvim`
if editing `{working_dir}/src/foo.txt` and then running `:New -> abc/123.txt`
- `abc/123.txt` will be created relative to working dir i.e. `{working_dir}/abc/123.txt`
- buffer will try to edit `{working_dir}/src/abc/123.txt` which doesn't exist (notice the `src` in there)

ig the question is should :New make a file relative to the working dir of neovim, or relative to the path of the file currently being edited. IMO, relative to Neovim's working path is a sensible choice.

EDIT: there are a few reasons that come to mind for file creation relative to $PWD instead of relative to the currently open file
1. directory autocomplete is looking from $PWD
2. what if there's no currently open file? does $PWD become the default?
3. in complex projects, it's probably easier(??) to just go from the root instead of something like "../../../src/app/_components/etc"

### To Reproduce

1. `cd working_dir`
4. `mkdir src/`
5. `echo "Hello" > src/foo.txt`
6. `nvim src/foo.txt`
7. `:New` then input "abc/123" as the argument
8. file won't open

### neovim version

```Text
Installed with homebrew 

$ nvim --version

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.1/share/nvim"

Run :checkhealth for more info
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
> abc/123.txt will be created relative to working dir i.e. `{working_dir}/abc/123.txt`
buffer will try to edit `{working_dir}/src/abc/123.txt` which doesn't exist (notice the src in there)

I cannot reproduce that issue?

> EDIT: there are a few reasons that come to mind for file creation relative to $PWD instead of relative to the currently open file

it's actually useful for many scenarios to *not* use the PWD. For example, If I am editing a submodule, say `.../lua/mymodule/mysubmodule.lua`, when I want to create a new submodule, I can just do `:New` and enter a new name, instead of having to specify and remember the whole path. Your PR, while fine on its own, breaks the existing workflows of people expecting this kind of behavior of the plugin, which is why I reverted it for now. (Sorry, should have paid attention before merging)

> 1. directory autocomplete is looking from $PWD
> 2. what if there's no currently open file? does $PWD become the default?
> 3. in complex projects, it's probably easier(??) to just go from the root instead of something like "../../../src/app/_components/etc"

These issues are valid, and a PR addressing them specifically instead of changing parent dir to working dir for all file operations would be better.

1. autocomplete with omnifunc is a less than ideal solution already – ideally, upstream plugin `dressing.nvim` should somehow have better cmp support.
2. in case of no open file, it makes sense to use the PWD instead, yeah
3. I don't follow what you mean.

In general, I think either an option, or some "smart" behavior (e.g. using the parent dir when you only enter a file name, using pwd when you enter a relative path, i.e. something with a slash) might make most sense, though I am not really decided what the best solution would be here

**Comment by BeauSLM** [comment]
> I cannot reproduce that issue?

I wasn't entirely correct. The dir `abc/` will be created but the file `abc/123.txt` won't be.

Could I provide a video demo or something to show repro? I can do with an init.lua that only installs lazy and Genghis. If there's another way I can provide clarity or demonstrate repro steps lmk.

The issue is in the new version. It comes from the fact that the `mkdir` call makes a directory relative to $PWD, but the new file path is constructed relative to the dir of the current file.

In particular:
```lua
local dir = expand("%:p:h") -- same directory, *not* pwd

// later...
local newFolder = vim.fs.dirname(newName) -- creates the new folder, but without {dir} prepended
                           -- ^^ dir not prepended here

local newFilePath = (op == "move-rename") and newName or dir .. "/" .. newName
                                                                                                    --   ^^ dir prepended here
```

> it's actually useful for many scenarios to _not_ use the PWD. For example, If I am editing a submodule, say `.../lua/mymodule/mysubmodule.lua`, when I want to create a new submodule, I can just do `:New` and enter a new name, instead of having to specify and remember the whole path. Your PR, while fine on its own, breaks the existing workflows of people expecting this kind of behavior of the plugin, which is why I reverted it for now.

This is fair. Specifying and remembering the whole path to the module is somewhat easier with tab autocomplete but yeah I agree its pretty bad.

> Even more, for some commands like e.g. file renaming, assuming the pwd instead of the parent dir would implicitly move files when you just want to change the name.

I never thought of that, definitely completely fair. Perhaps rename could auto populate the dirname of the current file so that when the new filename's typed it's already in the right dir? Bonus is ctrl-u would remove the path from the field so rename + move falls out easily. I.e. if renaming `$PWD/src/foo.txt` the prompt has `src/` and the cursor is right after.

I see that `moveAndRenameFile()` already prefills the current dir. Could `new` do the same?

> 3. I don't follow what you mean.

the relative path from `src/foo/bar/baz` to `src/abc/def/ghi/` is ugly (`../../../abc/def/ghi`). AFAIK the only way to make sure there's the right number of `..`s is squinting. It's a bit easier to go from the root cause tab complete gives a bit of robustness.

> In general, I think either an option, or some "smart" behavior (e.g. using the parent dir when you only enter a file name, using pwd when you enter a relative path, i.e. something with a slash) might make most sense, though I am not really decided what the best solution would be here

Honestly I'm wondering if populating the prompt with the relative path from $PWD would work.
- By default, new/renamed files end up in the same directory 
- instead of typing relative paths, just ctrl-w to go back one folder or ctrl-u to go back to $PWD

Also I apologize for any lack of clarity, I'm struggling to find a simple way to state my thoughts. Please let me know if there's anything I can elaborate on.

**Comment by BeauSLM** [comment]
actually giving it more thought, just prefilling the path of the file for file ops has some benefits

- ultimately the input will end up being the new path of the file that's being moved/renamed/duplicated. Just take the path and perform the appropriate operation, no sweat.
- easy to choose the path of the new file with ctrl-w, ctrl-u, and tab autocomplete
-  rename basically becomes unix `mv` command, no need for two separate ops.

On the downside its a touch cursed.

**Comment by BeauSLM** [comment]
I implemented this idea, could you take a look? I don't want to open a PR cause idk if the relative paths in the prompt and messages is too annoying, so I figured I could get your feedback first.

https://github.com/beauslm/nvim-genghis/tree/prefill_cwd

If a PR is preferred lmk
