### ISSUE TITLE
handling path in a manner consistent with nvim-tree

### ISSUE THREAD

**Issue by prncss-xyz** [chrisgrieser/nvim-genghis#4]
When inputing the new path:
- Prompt is prefilled with directory path relative to cwd.
- Modifing this path also modifies the file's path.
- Missing directories are created on the fly.

Can make a pull request if you are interested (your you can make it too).

**Comment by chrisgrieser** [comment]
well, since I do not use nvim-tree, I have no idea what exactly would be consistent with its behavior 😝 

so yeah, feel free to make a PR for it

**Comment by chrisgrieser** [comment]
maybe as a separate command though, since I think I quite like the simplicity of the current rename command?

**Comment by prncss-xyz** [comment]
Ok, I'll see what I kind do while preserving code's simplicity.

**Comment by chrisgrieser** [comment]
btw, I just found that vim has a builtin `mkdir` function, which saves us from using UNIX' `mkdir` for such a feature: https://neovim.io/doc/user/builtin.html#mkdir()

**Comment by chrisgrieser** [comment]
implemented with latest relase
