### ISSUE TITLE
Feature Request: Have an option to keep file extension on rename/duplicate

### ISSUE THREAD

**Issue by marcomayer** [chrisgrieser/nvim-genghis#45]
### Feature Requested

Would be great to have an option to keep the file extension on rename/duplicates as the new file name suggestion. 

Relevant code seems to be https://github.com/chrisgrieser/nvim-genghis/blob/4d01098310dae1fec3344a024e1f519f346ab9c2/lua/genghis/init.lua#L33. If I find the time I'll come up with a PR myself. Would you prefer this to be a config option or a parameter to the functions?

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
This is already the case. From the readme:

---
![Pasted image 2024-02-19 at 12 12 11@2x](https://github.com/chrisgrieser/nvim-genghis/assets/73286100/19556aa0-2ad2-4ce1-8189-e44ac9b09b66)
