### ISSUE TITLE
[Bug]: Options not displayed for `.moveToFolderInCwd` if cwd is within a hidden folder

### ISSUE THREAD

**Issue by ryankav** [chrisgrieser/nvim-genghis#46]
### Bug Description

When trying to move a file using `.moveToFolderInCwd` within a hidden folder, in my case `~/.config/nvim`, no options appear. I believe the cause of the issue is this: https://github.com/chrisgrieser/nvim-genghis/blob/1e6855be88e2266c612903dbc337222b59a06e44/lua/genghis/init.lua#L142

Assume changing this line to search on a relative path from cwd would resolve this issue. Happy to open a PR if wanted

### To Reproduce

Try and move a file to another folder when the current working directory is either a hidden directory or a descendant of a hidden directory eg:
```
mkdir .test
cd .test
mkdir a
mkdir b
echo "Hello, world" > a/test.txt
nvim .
```
Then try and move `test.txt` into directory b using `.moveToFolderInCwd`

### neovim version

```Text
v0.9.5
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
Ah yes, haven't thought about that case. Yeah, you can open a PR for it. 

Not sure what's the best approach here, since usually hidden folders only add noise, maybe an option, hm.

**Comment by ryankav** [comment]
This is roughly what I was thinking would be the desired approach. Tried to change as little as possible but happy to adapt if you'd prefer an alternative approach https://github.com/chrisgrieser/nvim-genghis/pull/47
