### ISSUE TITLE
Feature Request: tag version last supporting Neovim 0.9

### ISSUE THREAD

**Issue by alexmozaidze** [chrisgrieser/nvim-genghis#49]
### Feature Requested

Add a tag on git to the commit that last supported Neovim 0.9

This would help people stuck with older Neovim (like Termux users, or perhaps Debian users). This won't be a problem for long now that 0.10 is stable, but it would be nice to have the tag.

EDIT: The commit before the big refactor seems to be 01eeb090ea4947df6b6b9d8589b324b9f1aaf851

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
Can't you simply pin that commit?
Iirc, it's `commit = hash` with lazy.nvim

**Comment by alexmozaidze** [comment]
Yeah, but a tag would be nice.

**Comment by chrisgrieser** [comment]
"would be nice" without any functional benefit feels a bit unnecessary to me, sorry.
