### ISSUE TITLE
Feature Request: Make subcommand tab complete smarter

### ISSUE THREAD

**Issue by mcchrish** [chrisgrieser/nvim-genghis#50]
### Feature Requested

See how trouble does it. Where it smartly filter other options based on the current input

### Relevant Screenshot

https://github.com/user-attachments/assets/f6dbf837-e459-4525-889e-14affa6723d0

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
added some filtering, typing `ren` will now only complete the commands containing that string:
![Pasted image 2024-12-08 at 13 14 19@2x](https://github.com/user-attachments/assets/4a43d3ff-62a3-4dd9-a895-1c213bdeb58f)
