### ISSUE TITLE
[Bug]: Genghis ex command not available out of the box with lazy.nvim

### ISSUE THREAD

**Issue by rodrigoaguilera** [chrisgrieser/nvim-genghis#51]
### Bug Description

I am replacing eunuch with genghis just to give it a try but following the installation instructions for lazy doesn't make the :Genghis command available 

### To Reproduce

Install plugin with lazy just like the readme 
```
-- lazy.nvim
{ 
	"chrisgrieser/nvim-genghis", 
	dependencies = "stevearc/dressing.nvim"
},
```
:Lazy reports it as installed but typing `:Genghis` fails with E492: not an editor command.

Writing `:lua require('genghis')` makes the command `:Genghis` available.
also loading it as 
```
  {
    "chrisgrieser/nvim-genghis",
    dependencies = "stevearc/dressing.nvim",
    init = function()
      --
      require('genghis')
    end,
  }
```
Also works.

Looking at other plugins I see the ship with a `plugin/NAME_OF_PLUGIN.lua` file that usually does this kind of setup like 
https://github.com/nvim-treesitter/nvim-treesitter/blob/master/plugin/nvim-treesitter.lua

### neovim version

```Text
0.10.2
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
That's technically not a bug. You most likely have `lazy = false` set as package default in your lazy.nvim installation. In this case, you need to add this instead as installation snippet, since lazy does not load plugin ex commands if the plugin is not loaded. 

```lua
{ 
	"chrisgrieser/nvim-genghis", 
	dependencies = "stevearc/dressing.nvim"
	cmd = "Genghis",
},
```

Added to the docs to avoid this issue for future users. As a heads-up, please note that this issue will affect any plugin using ex commands, not just genghis.

**Comment by rodrigoaguilera** [comment]
That solution didn't work for me, This is the error I get
![image](https://github.com/user-attachments/assets/992b2225-742c-48a3-aea6-624bbcbaa084)

I didn't touch any defaults from lazy. I install it with the suggested snippet
https://lazy.folke.io/installation

Other plugins I use with Ex commands that work fine are eunuch, ale, treesitter. I wonder what is different.

The workaround is fine for me but if you are very interested in fixing this I can assemble a dockerfile to reproduce it.

**Comment by chrisgrieser** [comment]
No need, I can reproduce. Looks like it is a lazy.nvim bug that occurs when you do not have any `opts` set. Even if just using the default config, you apparently need to pass an empty table `opts = {}` for lazy to work here:

```lua
{ 
	"chrisgrieser/nvim-genghis", 
	dependencies = "stevearc/dressing.nvim"
	cmd = "Genghis",
	opts = {},  -- <-- add this
},
```

Really weird lazy.nvim bug. You could consider opening a bug at lazy.nvim
