### ISSUE TITLE
Feature Request: Demo Gif/Video

### ISSUE THREAD

**Issue by alr86** [chrisgrieser/nvim-genghis#53]
### Feature Requested

Add a demo gif/video in README

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
It's just renaming files, nothing where I personally find adding a demo useful, to be frank. 

Feel free to make a PR though, if you like.

**Comment by chrisgrieser** [comment]
well, they can't hurt either, so I just added one simple screenshot.
