### ISSUE TITLE
Provide `:Commands` like `vim-eunuch`

### ISSUE THREAD

**Issue by mrjones2014** [chrisgrieser/nvim-genghis#6]
I think it'd be a good idea and make it a lot easier to switch if you provided the same command mappings as `vim-eunuch` so you could run `:Delete!`, `:Rename`, `Chmod +x`, `:Move` etc.

**Comment by mrjones2014** [comment]
You can use [`:h nvim_create_user_command()`](https://neovim.io/doc/user/api.html#nvim_create_user_command()) for this. It can be called from Lua by `vim.api.nvim_create_user_command`

**Comment by chrisgrieser** [comment]
Hi! I actually intentionally decided against doing so. Reason being that using `:Rename` puts you into the cmdline, so that plugins like dressing will not work. 

Using `vim.ui.input` allows for plugins like dressing to step in, which among other things, also enables normal mode commands during the name editing.

**Comment by mrjones2014** [comment]
A `:Rename` command could just trigger the `vim.ui.input` though

**Comment by megalithic** [comment]
👆 came here to mention the same. it also helps lazy loading plugin managers like `lazy.nvim` and even `packer.nvim` to lazy load on certain commands (though, i know you can do the same with keybindings for both of those package managers). 

Yes, one can simply add their own custom user commands in their own configs, but it'd be nice if these existed out of the box.

That said, LOVE the plugin and also, love your hammerspoon config, too. :)

**Comment by chrisgrieser** [comment]
fine, as there seems to be more interest in this, re-opening. 

if anyone already has user commands made, feel free to PR them

**Comment by chrisgrieser** [comment]
implemented via #8, thx @saccarosium
